<OpenScreen>

    name: name
    submit_button: submit_button
    FloatLayout:
        size: root.size
        TextInput:
            id: name
            hint_text: "Enter your name"
            size_hint: .2, .1
            pos_hint: {'x':.4, 'y':.6}
            multiline: False
        Button:
            id: submit_button
            size_hint: .2, .1
            pos_hint: {'x':.4, 'y':.4}
            text: "Submit"
            on_press: root.submit_btn()
